s4s/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login,logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 's4s.views.home', name='home'),
    # url(r'^s4s/', include('s4s.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^vetbiz/',include('vetbiz.urls')),
    url(r'^$',include('vetbiz.urls')),
    url(r'^accounts/login/$',login),
    url(r'^accounts/logout/$',logout)
)

vetbiz/urls.py
from django.conf.urls import patterns,url

from vetbiz import views
from vetbiz import api

urlpatterns=patterns('',
        url(r'api/getbiz/$',api.getbiz),
        url(r'api/updatebiz/$',api.updatebiz),
        url(r'api/searchbiz/$',api.searchbiz),
        url(r'api/signin/$',api.signin),
        url(r'api/unique/$',api.unique),
        url(r'api/signup/$',api.signup),
        url(r'api/dologout/$',api.dologout),
        url(r'api/checkin/$',api.checkin),
        url(r'api/donate/$',api.donate),
        url(r'api/offers/$',api.offers),
        url(r'api/jobs/$',api.jobs),
        url(r'api/charities/$',api.charities),
        url(r'api/places/$',api.places),
        url(r'search/$',views.search),
        url(r'search$',views.search),
        url(r'checkins/$',views.checkins),
        url(r'checkins$',views.checkins),
        url(r'donations/$',views.donations),
        url(r'donations$',views.donations),
        url(r'offers/$',views.offers),
        url(r'createoffer/(?P<place_id>\d+)',views.createoffer),
        url(r'saveofferedit/(?P<offer_id>\d+)',views.saveofferedit),
        url(r'offeredit/(?P<offer_id>\d+)',views.offeredit),
        url(r'deleteoffer/(?P<offer_id>\d+)',views.deleteoffer),
        url(r'saveoffer/(?P<place_id>\d+)',views.saveoffer),
        url(r'offers$',views.offers),
        url(r'offer/(?P<offer_id>\d+)',views.offer),
        url(r'createjob/(?P<place_id>\d+)',views.createjob),
        url(r'createoffer/(?P<place_id>\d+)',views.createoffer),
        url(r'savejobedit/(?P<job_id>\d+)',views.savejobedit),
        url(r'jobedit/(?P<job_id>\d+)',views.jobedit),
        url(r'deletejob/(?P<job_id>\d+)',views.deletejob),
        url(r'savejob/(?P<place_id>\d+)',views.savejob),
        url(r'job/(?P<job_id>\d+)',views.job),
        url(r'saveplace/(?P<place_id>\d+)',views.saveplace),
        url(r'place/(?P<place_id>\d+)',views.place),
        url(r'charity/(?P<charity_id>\d+)',views.charity),
        url(r'placeadmin/(?P<place_id>\d+)',views.placeadmin),
        url(r'placeedit/(?P<place_id>\d+)',views.placeedit),
        url(r'jobs/$',views.jobs),
        url(r'jobs$',views.jobs),
        url(r'places$',views.places),
        url(r'places/$',views.places),
        url(r'charities$',views.charities),
        url(r'charities/$',views.charities),
        url(r'profile$',views.profile),
        url(r'profile/$',views.profile),
        url(r'signin/$',views.signin),
        url(r'signin$',views.signin),
        url(r'signup/$',views.signup),
        url(r'signup$',views.signup),
        url(r'/$',views.search),
        url(r'$',views.search))

vetbiz/models.py
from django.db import models
from django.forms import ValidationError
from django import forms
from django.contrib.auth.models import User
from django.contrib.admin import widgets

class UserProfile(models.Model):
    user=models.OneToOneField(User)
    veteran=models.BooleanField(default=False)
    branch=models.CharField(max_length=200)
    points=models.IntegerField(default=0)
    checkins=models.IntegerField(default=0)
    last_lat=models.FloatField(default=0)
    last_lon=models.FloatField(default=0)
    def num_redemptions(self):
        return Redemption.objects.filter(user=self).count()

    def __unicode__(self):
        return self.user.username

class Category(models.Model):
    name=models.CharField(max_length=200)
    def __unicode__(self):
        return self.name

class Business(models.Model):
    name=models.CharField(max_length=200)
    category=models.ForeignKey(Category,null=True,blank=True)
    address=models.CharField(max_length=200,default='')
    lat=models.FloatField(default=0)
    lon=models.FloatField(default=0)
    veteran_owned=models.BooleanField(default=False)
    veteran_discounts=models.BooleanField(default=False)
    disabled_veteran=models.BooleanField(default=False)
    points_per_checkin=models.IntegerField(default=10)
    description=models.TextField(null=True,blank=True)
    image_url=models.URLField(null=True,blank=True)
    logo_url=models.URLField(null=True,blank=True)
    pin_url=models.URLField(null=True,blank=True)
    phone=models.CharField(max_length=200,null=True,blank=True)
    email=models.CharField(max_length=200,null=True,blank=True)
    url=models.CharField(max_length=200,null=True,blank=True)
    admin=models.ForeignKey(User,null=True,blank=True)
    page_views=models.IntegerField(default=0)

    def num_checkins(self):
        return Checkin.objects.filter(business=self).count()
    
    def num_offers(self):
        return Offer.objects.filter(business=self).count()
    
    def num_redemptions(self):
        return Redemption.objects.filter(offer__business=self).count()
    
    def num_redemptions(self):
        return Redemption.objects.filter(offer__business=self).count()

    def __unicode__(self):
        return self.name

class BusinessForm(forms.ModelForm):
	class Meta:
		model=Business
		exclude=['admin','page_views']
        

class Checkin(models.Model):
    user=models.ForeignKey(User)
    business=models.ForeignKey(Business)
    date=models.DateTimeField(auto_now=True)

    # when user checks in they get some points based on business setting for points per checkin...
    def save(self,*args,**kwargs):
        super(Checkin,self).save(*args,**kwargs)
        # TODO: if user did not check in already today...
        #if not Checkin.objects.exists(user=self.user,business=self.business,date__date=self.date.date):
        # TODO: get user profile
        #self.user.points=self.user.points+self.business.points_per_checkin
        #self.user.checkins=self.user.checkins+1
        
        #self.user.save()
        

    def __unicode__(self):
        return self.business.name

class BusinessPageView(models.Model):
    user=models.ForeignKey(User)
    business=models.ForeignKey(Business)
    date=models.DateTimeField(auto_now=True)
	
    def __unicode__(self):
        return self.business.name

class Offer(models.Model):
    business=models.ForeignKey(Business)
    title=models.CharField(max_length=200)
    description=models.CharField(max_length=200,null=True,blank=True)
    points=models.IntegerField(default=0)
    veterans_only=models.BooleanField(default=False)
    start_date=models.DateTimeField(auto_now_add=True)
    end_date=models.DateTimeField(null=True,blank=True)
    page_views=models.IntegerField(default=0)
    def num_redemptions(self):
        return Redemption.objects.filter(offer=self).count()
    def __unicode__(self):
        return self.title

class OfferForm(forms.ModelForm):
    class Meta:
        model=Offer
        exclude=['page_views']
        widgets={'business':forms.widgets.HiddenInput(),'end_date':widgets.AdminDateWidget()}

class Charity(models.Model):
    name=models.CharField(max_length=200)
    description=models.TextField(null=True,blank=True)
    image_link=models.CharField(max_length=200,null=True,blank=True)
    link=models.CharField(max_length=200,null=True,blank=True)
    donated_points=models.IntegerField(default=0)     
    
    def __unicode__(self):
        return self.name

class Donation(models.Model):
    user=models.ForeignKey(User)
    charity=models.ForeignKey(Charity)
    points=models.IntegerField()
    date=models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.charity.name

class Job(models.Model):
    business=models.ForeignKey(Business)
    title=models.CharField(max_length=200)
    description=models.TextField(null=True,blank=True)
    category=models.CharField(max_length=200,null=True,blank=True)
    start_date=models.DateTimeField(auto_now_add=True)
    end_date=models.DateTimeField(null=True,blank=True)
    contact_phone=models.CharField(max_length=200,null=True,blank=True)
    contact_email=models.CharField(max_length=200,null=True,blank=True)
    contact_link=models.CharField(max_length=200,null=True,blank=True)
    education_level=models.CharField(max_length=200,null=True,blank=True)
    experience_years=models.CharField(max_length=200,null=True,blank=True)
    reference_code=models.CharField(max_length=200,null=True,blank=True)
    page_views=models.IntegerField(default=0)

    def address(self):
        return self.business.address

    def __unicode__(self):
        return self.title

class JobForm(forms.ModelForm):
    class Meta:
        model=Job
        exclude=['page_views','education_level','experience_years']
        widgets={'business':forms.widgets.HiddenInput(),
				'start_date':widgets.AdminDateWidget(),
				'end_date':widgets.AdminDateWidget()}

class Redemption(models.Model):
    offer=models.ForeignKey(Offer)
    user=models.ForeignKey(User)
    date=models.DateTimeField(auto_now=True)

    def user_name(self):
        return self.user.username
    
    def business(self):
        return self.offer.business.name
    
    def category(self):
        return self.offer.business.category.name

    def offer_title(self):
        return self.offer.title

    def offer_points(self):
        return self.offer.points

    def save(self,*args,**kwargs):
        # TODO: get user profile...
        #if self.user.points<self.offer.points:
        #    raise ValidationError("User does not have enough points for this offer.")
        #if self.offer.veterans_only and not self.user.veteran:
        #    raise ValidationError("User must be a veteran for this offer.")
        # TODO: make sure offer already started and is not expired...

        super(Redemption,self).save(*args,**kwargs)
        # TODO: if user did not check in already today...
        #if not Checkin.objects.exists(user=self.user,business=self.business,date__date=self.date.date):
        #self.user.points=self.user.points-self.offer.points
        
        #self.user.save()
    

vetbiz/templates/vetbiz/charities.html
{% extends "vetbiz/base.html" %}
{% block tabs %}
    <ul class="nav navbar-nav">
        <li><a href="/vetbiz/">Map</a></li>
        <li><a href="/vetbiz/places/">Places</a></li>
        <li><a href="/vetbiz/offers/">Offers</a></li>
        <li><a href="/vetbiz/jobs/">Jobs</a></li>
        <li class="active"><a href="/vetbiz/charities/">Charities</a></li>
    </ul>
{% endblock %}
{% block content %}

    <style>
    body {
                    background: url(/static/img/bg_careers_help.jpg) no-repeat left top fixed; 
                                -webkit-background-size: cover;
                                -moz-background-size: cover;
                                -o-background-size: cover;
                                background-size: cover;
                                                                            }


    </style>
    <div class="col-sm-10 col-sm-offset-1 well" style="margin-top:50px">
        <table class="table">
    <thead>
        <tr>
            <th>
                Charity
            </th>
            <th>
                Donated Points
            </th>
        </tr>
    </thead>
    <tbody>
        {% for charity in charities%}
        <tr>
            <td>
                <a href="/vetbiz/charity/{{charity.id}}">{{charity.name}}</a>
            </td>
            <td>
                {{charity.donated_points}}
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>
</div>


{% endblock %}

vetbiz/templates/vetbiz/checkins.html
{% extends "vetbiz/base.html" %}
{% block content %}

    <style>
    body {
                    background: url(/static/img/bg_careers_help.jpg) no-repeat left top fixed; 
                                -webkit-background-size: cover;
                                -moz-background-size: cover;
                                -o-background-size: cover;
                                background-size: cover;
                                                                            }


    </style>
    <div class="col-sm-10 col-sm-offset-1 well" style="margin-top:50px">
        <table class="table">
    <thead>
        <tr>
            <th>
                Place
            </th>
            <th>
                Address
            </th>
            <th>
                Date
            </th>
        </tr>
    </thead>
    <tbody>
        {% for checkin in checkins%}
        <tr>
            <td>
                <a href="/vetbiz/place/{{checkin.business.id}}">{{checkin.business.name}}</a>
            </td>
            <td>
                {{checkin.business.address}}
            </td>
            <td>
                {{checkin.date}}
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>
</div>


{% endblock %}

vetbiz/templates/vetbiz/createjob.html
{% extends "vetbiz/base.html" %}
{% block tabs %}
    <ul class="nav navbar-nav">
        <li><a href="/vetbiz/">Map</a></li>
        <li class="active"><a href="/vetbiz/places/">Places</a></li>
        <li><a href="/vetbiz/offers/">Offers</a></li>
        <li><a href="/vetbiz/jobs/">Jobs</a></li>
        <li><a href="/vetbiz/charities/">Charities</a></li>
    </ul>
{% endblock %}
{% block content %}

    <style>
    body {
                    background: url(/static/img/bg_careers_help.jpg) no-repeat left top fixed; 
                                -webkit-background-size: cover;
                                -moz-background-size: cover;
                                -o-background-size: cover;
                                background-size: cover;
                                                                            }
	
	.googlemap{
		border-style:solid;
		border-width:1px;
		border-color:#aaa;
		margin-top:1px;
		margin-bottom:10px;
	}
	.place-image{
		max-width:300px;
		height:auto;
		margin-bottom:20px;
	}
	.logo-image{
		max-width:80px;
		height:auto;
	}
	
	input{width:400px}
	textarea{width:400px}
	select{width:400px}	

    </style>
    <div class="col-sm-10 col-sm-offset-1 panel" style="margin-top:50px">
			<h3>{{place.name}}</h3>
			<address>
			    {{place.address}}
			</address>
			<h3>Create Job</h3>
			<form role="form" action="/vetbiz/savejob/{{place.id}}" method="POST">
				{% csrf_token %}
				<table>
				{{ form.as_table }}
				</table>
				<a href="/vetbiz/placeadmin/{{place.id}}" class="btn btn-default">Cancel</a>
				<button type="submit" class="btn btn-primary">Save</button>
			</form>
	</div>
    
    <script>
    
        $(document).ready(function(){
            $('input').addClass('form-control').css('width','400px').css('margin-bottom','10px');    
            $('textarea').addClass('form-control').css('width','400px').css('margin-bottom','10px');    
    });

</script>
{% endblock %}

vetbiz/templates/vetbiz/createoffer.html
{% extends "vetbiz/base.html" %}
{% block tabs %}
    <ul class="nav navbar-nav">
        <li><a href="/vetbiz/">Map</a></li>
        <li class="active"><a href="/vetbiz/places/">Places</a></li>
        <li><a href="/vetbiz/offers/">Offers</a></li>
        <li><a href="/vetbiz/jobs/">Jobs</a></li>
        <li><a href="/vetbiz/charities/">Charities</a></li>
    </ul>
{% endblock %}
{% block content %}

    <style>
    body {
                    background: url(/static/img/bg_careers_help.jpg) no-repeat left top fixed; 
                                -webkit-background-size: cover;
                                -moz-background-size: cover;
                                -o-background-size: cover;
                                background-size: cover;
                                                                            }
	
	.googlemap{
		border-style:solid;
		border-width:1px;
		border-color:#aaa;
		margin-top:1px;
		margin-bottom:10px;
	}
	.place-image{
		max-width:300px;
		height:auto;
		margin-bottom:20px;
	}
	.logo-image{
		max-width:80px;
		height:auto;
	}
	
	input{width:400px}
	textarea{width:400px}
    select{width:400px}
    </style>
    <div class="col-sm-10 col-sm-offset-1 panel" style="margin-top:50px">
			<h3>{{place.name}}</h3>
			<address>
			    {{place.address}}
			</address>
			<h3>Create Offer</h3>
			<form role="form" action="/vetbiz/saveoffer/{{place.id}}" method="POST">
				{% csrf_token %}
				<table>
				{{ form.as_table }}
				</table>
				<a href="/vetbiz/placeadmin/{{place.id}}" class="btn btn-default">Cancel</a>
				<button type="submit" class="btn btn-primary">Save</button>
			</form>
	</div>
    
    <script>
    
        $(document).ready(function(){
            $('input').addClass('form-control').css('width','400px').css('margin-bottom','10px');    
    });

</script>
            
{% endblock %}

vetbiz/templates/vetbiz/donations.html
{% extends "vetbiz/base.html" %}
{% block content %}

    <style>
    body {
                    background: url(/static/img/bg_careers_help.jpg) no-repeat left top fixed; 
                                -webkit-background-size: cover;
                                -moz-background-size: cover;
                                -o-background-size: cover;
                                background-size: cover;
                                                                            }


    </style>
    <div class="col-sm-10 col-sm-offset-1 well" style="margin-top:50px">
        <table class="table">
    <thead>
        <tr>
            <th>
                Charity
            </th>
            <th>
                Points
            </th>
            <th>
                Date
            </th>
        </tr>
    </thead>
    <tbody>
        {% for donation in donations%}
        <tr>
            <td>
                <a href="/vetbiz/charity/{{donation.charity.id}}">{{donation.charity.name}}</a>
            </td>
            <td>
                {{donation.points}}
            </td>
            <td>
                {{donation.date}}
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>
</div>


{% endblock %}

vetbiz/templates/vetbiz/offer.html
{% extends "vetbiz/base.html" %}
{% block tabs %}
    <ul class="nav navbar-nav">
        <li><a href="/vetbiz/">Map</a></li>
        <li><a href="/vetbiz/places/">Places</a></li>
        <li class="active"><a href="/vetbiz/offers/">Offers</a></li>
        <li><a href="/vetbiz/jobs/">Jobs</a></li>
        <li><a href="/vetbiz/charities/">Charities</a></li>
    </ul>
{% endblock %}
{% block content %}
    <style>
    body {
                    background: url(/static/img/bg_benefits_money.jpg) no-repeat left top fixed; 
                                -webkit-background-size: cover;
                                -moz-background-size: cover;
                                -o-background-size: cover;
                                background-size: cover;
                                                                            }

  @media screen{
     #printSection{ display:none;}}

   @media print{
      body * {visibility:hidden;}
      #printSection, #printSection * {visibility:visible;}
      #printSection { position:absolute; left:0;top:0;}}

    </style>
    
    <div class="col-sm-10 col-sm-offset-1 well" style="margin-top:50px">
        <h2><a href="/vetbiz/place/{{offer.business.id}}">{{offer.business.name}}</a></h2>
        <address>
            {{offer.business.address}}
        </address>
        <h2>{{offer.title}}
    {% if offer.veterans_only %}
    *
    {% endif %}
        </h2>
	{{offer.description}}
<div id="qrcode" style="width:100px; height:100px; margin-top:20px;"></div>
    {% if offer.veterans_only %}
        <br>
        <b>* Veterans Only</b>    
    {% endif %}
    <br><br>
        <a href="javascript:window.print()">Print Offer</a> 
     </div>
    <div class="printable" id="printSection">
        <h2>{{offer.business.name}}</h2>
        <address>
            {{offer.business.address}}
        </address>
        <h2>{{offer.title}}
    {% if offer.veterans_only %}
    *
    {% endif %}
</h2>
{{offer.description}}
<div id="qrcodeprintable" style="width:100px; height:100px; margin-top:20px;"></div>
    {% if offer.veterans_only %}
        <br>
        <b>* Veterans Only</b>    
    {% endif %}
	<br><br>
        www.StarsOnStripes.com
    </div>
    <script type="text/javascript">

        function makeQrCode(id,val)
        {
            var qrcode=new QRCode(document.getElementById(id),{
width:100,
height:100});

            qrcode.makeCode(val);
        }
        $(document).ready(function(){
                makeQrCode("qrcode","{{offer.business.id}}_{{offer.id}}");        
                makeQrCode("qrcodeprintable","{{offer.business.id}}_{{offer.id}}");        
                
        });

    </script>
{% endblock %}

vetbiz/templates/vetbiz/offers.html
{% extends "vetbiz/base.html" %}
{% block tabs %}
    <ul class="nav navbar-nav">
        <li><a href="/vetbiz/">Map</a></li>
        <li><a href="/vetbiz/places/">Places</a></li>
        <li class="active"><a href="/vetbiz/offers/">Offers</a></li>
        <li><a href="/vetbiz/jobs/">Jobs</a></li>
    </ul>
{% endblock %}
{% block content %}
    <style>
    body {
                    background: url(/static/img/bg_benefits_money.jpg) no-repeat left top fixed; 
                                -webkit-background-size: cover;
                                -moz-background-size: cover;
                                -o-background-size: cover;
                                background-size: cover;
                                                                            }


    </style>
    <div class="col-sm-10 col-sm-offset-1 well" style="margin-top:50px">
<table class="table">
    <thead>
        <tr>
            <th>
                Offer
            </th>
            <th>
                Place
            </th>
            <th>
                Address 
            </th>
        </tr>
    </thead>
    <tbody>
        {% for offer in offers %}
        <tr>
            <td>
                <a href="/vetbiz/offer/{{offer.id}}">{{offer.title}}</a>
            </td>
            <td>
                <a href="/vetbiz/place/{{offer.business.id}}">{{offer.business.name}}</a>
            </td>
            <td>
                {{offer.business.address}}
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>
</div>

{% endblock %}

vetbiz/templates/vetbiz/place.html
{% extends "vetbiz/base.html" %}
{% block tabs %}
    <ul class="nav navbar-nav">
        <li><a href="/vetbiz/">Map</a></li>
        <li class="active"><a href="/vetbiz/places/">Places</a></li>
        <li><a href="/vetbiz/offers/">Offers</a></li>
        <li><a href="/vetbiz/jobs/">Jobs</a></li>
        <li><a href="/vetbiz/charities/">Charities</a></li>
    </ul>
{% endblock %}
{% block content %}

    <style>
    body {
                    background: url(/static/img/bg_careers_help.jpg) no-repeat left top fixed; 
                                -webkit-background-size: cover;
                                -moz-background-size: cover;
                                -o-background-size: cover;
                                background-size: cover;
                                                                            }
	
	.googlemap{
		border-style:solid;
		border-width:1px;
		border-color:#aaa;
		margin-top:1px;
		margin-bottom:10px;
	}
	.place-image{
		max-width:300px;
		height:auto;
		margin-bottom:20px;
	}
	.logo-image{
		max-width:80px;
		height:auto;
	}
	

    </style>
    <div class="col-sm-10 col-sm-offset-1 panel" style="margin-top:50px">
        <h2>{{place.name}}</h2>
        {% if place.logo_url %}<img class="logo-image" src="{{place.logo_url}}">{% endif %}
	<address>
            {{place.address}}
	    {% if place.phone %}
		<br>Phone: {{place.phone}}
	    {% endif %}
	    {% if place.email %}
		<br>Email: {{place.email}}
	    {% endif %}
	{% if place.url %}
		<br><a href="{{place.url}}">{{place.url}}</a>
	{% endif %}
	
        </address>
	<div class="row">
	<div class="col-sm-6" style="width:320px">
		{% if place.image_url %}
			<img class="place-image" src="{{place.image_url}}">
		{% endif %}
		<img class="googlemap" width="300" height="200" src="http://maps.googleapis.com/maps/api/staticmap?center={{place.lat}},{{place.lon}}&maptype=roadmap&markers=color:blue%7C{{place.lat}},{{place.lon}}&sensor=false&zoom=13&size=400x300"/>
		<br>
		{% if place.veteran_owned %}
		    <span class="label label-info">Veteran Owned</span>
		{% endif %}
		{% if place.veteran_discounts %}
		    <span class="label label-success">Veteran Discounts</span>
		    {% endif %}
		{% if place.disabled_veteran %}
		    <span class="label label-success">Disabled Veteran</span>
		    {% endif %}
	</div>
	<div class="col-sm-6" style="vertical-align:top;">
		{% if place.description %}
		{{place.description|safe}}
		{% endif %}
	</div>
	</div>
	<div class="row">
		<div class="col-sm-12">	
	{% if place.offer_set.all %}
		<h2>Offers</h2>
		{% for offer in place.offer_set.all %}
		<p><a href="/vetbiz/offer/{{offer.id}}">{{offer.title}}</a></p>
		{% endfor %}
	{% endif %}

	{% if place.job_set.all %}
		<h2>Jobs</h2>
		{% for job in place.job_set.all %}
		<p><a href="/vetbiz/job/{{job.id}}">{{job.title}}</a></p>
		{% endfor %}
	{% endif %}
	<br>
	{% if user.username %}
        	<button id="checkin-button" class="btn btn-success">Check in!</button>
    	{% else %}
		Log In or Sign Up to use the Check-in feature!
	{% endif %}
	</div>
	</div>
	</div>
    
    <script>
    
        $(document).ready(function(){

            $('#checkin-button').click(function(){
                checkin('{{place.id}}',function(msg){
                    $('#checkin-button').attr('disabled','disabled').html('You checked in!');
                    $('#points-badge').html(msg);
                });
            });
            });
    </script>
{% endblock %}

vetbiz/templates/vetbiz/placeedit.html
{% extends "vetbiz/base.html" %}
{% block tabs %}
    <ul class="nav navbar-nav">
        <li><a href="/vetbiz/">Map</a></li>
        <li class="active"><a href="/vetbiz/places/">Places</a></li>
        <li><a href="/vetbiz/offers/">Offers</a></li>
        <li><a href="/vetbiz/jobs/">Jobs</a></li>
        <li><a href="/vetbiz/charities/">Charities</a></li>
    </ul>
{% endblock %}
{% block content %}

    <style>
    body {
                    background: url(/static/img/bg_careers_help.jpg) no-repeat left top fixed; 
                                -webkit-background-size: cover;
                                -moz-background-size: cover;
                                -o-background-size: cover;
                                background-size: cover;
                                                                            }
	
	.googlemap{
		border-style:solid;
		border-width:1px;
		border-color:#aaa;
		margin-top:1px;
		margin-bottom:10px;
	}
	.place-image{
		max-width:300px;
		height:auto;
		margin-bottom:20px;
	}
	.logo-image{
		max-width:80px;
		height:auto;
	}
	input{width:400px}
	textarea{width:400px}
	select{width:400px}	

    </style>
    <div class="col-sm-10 col-sm-offset-1 panel" style="margin-top:50px">
	
			<h3>Edit Business Info</h3>
			<form role="form" action="/vetbiz/saveplace/{{place.id}}" method="POST">
				{% csrf_token %}
				<table>
				{{ form.as_table }}
				</table>
				<a href="/vetbiz/placeadmin/{{place.id}}" class="btn btn-default">Cancel</a>
				<button type="submit" class="btn btn-primary">Save</button>
			</form>
	</div>
    
    <script>
    
        $(document).ready(function(){
            $('input').addClass('form-control').css('width','400px').css('margin-bottom','10px');    
            $('textarea').addClass('form-control').css('width','400px').css('margin-bottom','10px');    
            $('select').addClass('form-control').css('width','400px').css('margin-bottom','10px');    
    });

</script>
{% endblock %}